"""initial schema

Revision ID: 3275ca2f94f9
Revises: 
Create Date: 2026-04-13 15:04:26.223018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3275ca2f94f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('root_url', sa.String(), nullable=False),
    sa.Column('normalized_host', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('root_url', name=op.f('uq_sites_root_url'))
    )
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_reason', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('strategy', sa.String(), nullable=True),
    sa.Column('max_depth', sa.SmallInteger(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('pages_queued', sa.Integer(), nullable=False),
    sa.Column('pages_completed', sa.Integer(), nullable=False),
    sa.Column('llms_txt_s3_key', sa.String(), nullable=True),
    sa.Column('bundle_s3_key', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("state IN ('discovering', 'processing', 'completed', 'failed')", name=op.f('ck_runs_valid_state')),
    sa.CheckConstraint("trigger_reason IN ('on_demand', 'cron')", name=op.f('ck_runs_valid_trigger_reason')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_runs_site_id_sites')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index('idx_runs_site_created', 'runs', ['site_id', 'created_at'], unique=False)
    op.create_index('uq_runs_site_inflight', 'runs', ['site_id'], unique=True, postgresql_where=sa.text("state IN ('discovering', 'processing')"))
    op.create_table('run_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('normalized_url', sa.String(), nullable=False),
    sa.Column('depth', sa.SmallInteger(), nullable=False),
    sa.Column('fetch_status', sa.String(), nullable=False),
    sa.Column('page_status', sa.String(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('html_s3_key', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fetch_status IN ('queued', 'fetched', 'failed')", name=op.f('ck_run_pages_valid_fetch_status')),
    sa.CheckConstraint("page_status IN ('UNCHANGED', 'CHANGED', 'NEW', 'REMOVED', 'FAILED')", name=op.f('ck_run_pages_valid_page_status')),
    sa.CheckConstraint('depth >= 0', name=op.f('ck_run_pages_valid_depth')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_pages_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_pages')),
    sa.UniqueConstraint('run_id', 'normalized_url', name='uq_run_page_url')
    )
    op.create_index('idx_run_pages_run', 'run_pages', ['run_id'], unique=False)
    op.create_index('idx_run_pages_status', 'run_pages', ['run_id', 'fetch_status', 'page_status'], unique=False)
    op.create_table('site_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_url', sa.String(), nullable=False),
    sa.Column('last_content_hash', sa.String(), nullable=True),
    sa.Column('last_etag', sa.String(), nullable=True),
    sa.Column('last_modified', sa.String(), nullable=True),
    sa.Column('last_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_html_s3_key', sa.String(), nullable=True),
    sa.Column('last_seen_run_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_run_id'], ['runs.id'], name=op.f('fk_site_pages_last_seen_run_id_runs')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_pages_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_pages')),
    sa.UniqueConstraint('site_id', 'normalized_url', name='uq_site_page_url')
    )
    op.create_index('idx_site_pages_active', 'site_pages', ['site_id', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_site_pages_active', table_name='site_pages')
    op.drop_table('site_pages')
    op.drop_index('idx_run_pages_status', table_name='run_pages')
    op.drop_index('idx_run_pages_run', table_name='run_pages')
    op.drop_table('run_pages')
    op.drop_index('uq_runs_site_inflight', table_name='runs', postgresql_where=sa.text("state IN ('discovering', 'processing')"))
    op.drop_index('idx_runs_site_created', table_name='runs')
    op.drop_table('runs')
    op.drop_table('sites')
    # ### end Alembic commands ###
