"""slice-4 render-mode contract

Revision ID: 73512bb8daa9
Revises: 3275ca2f94f9
Create Date: 2026-04-14 12:53:57.754796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73512bb8daa9"
down_revision: Union[str, Sequence[str], None] = "3275ca2f94f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("run_pages", sa.Column("render_mode", sa.String(), nullable=False))
    op.create_check_constraint(
        "ck_run_pages_valid_render_mode",
        "run_pages",
        "render_mode IN ('http', 'spa')",
    )
    op.drop_constraint("ck_run_pages_valid_fetch_status", "run_pages", type_="check")
    op.add_column(
        "run_pages", sa.Column("fetch_started_at", sa.DateTime(), nullable=True)
    )
    op.create_check_constraint(
        "ck_run_pages_valid_fetch_status",
        "run_pages",
        "fetch_status IN ('queued', 'fetch_in_progress', 'fetched', 'failed')",
    )
    op.add_column(
        "runs", sa.Column("processing_enqueued_at", sa.DateTime(), nullable=True)
    )
    op.drop_column("runs", "strategy")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runs", sa.Column("strategy", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("runs", "processing_enqueued_at")
    op.drop_constraint("ck_run_pages_valid_fetch_status", "run_pages", type_="check")
    op.drop_column("run_pages", "fetch_started_at")
    op.create_check_constraint(
        "ck_run_pages_valid_fetch_status",
        "run_pages",
        "fetch_status IN ('queued', 'fetched', 'failed')",
    )
    op.drop_constraint("ck_run_pages_valid_render_mode", "run_pages", type_="check")
    op.drop_column("run_pages", "render_mode")
    # ### end Alembic commands ###
