from typing import Literal, TypeAlias


FETCH_STATUS_QUEUED = "queued"
FETCH_STATUS_FETCH_IN_PROGRESS = "fetch_in_progress"
FETCH_STATUS_FETCHED = "fetched"
FETCH_STATUS_FAILED = "failed"

PAGE_STATUS_NEW = "NEW"
PAGE_STATUS_UNCHANGED = "UNCHANGED"
PAGE_STATUS_CHANGED = "CHANGED"
PAGE_STATUS_REMOVED = "REMOVED"
PAGE_STATUS_FAILED = "FAILED"

FetchStatusValue: TypeAlias = Literal[
    FETCH_STATUS_QUEUED,
    FETCH_STATUS_FETCH_IN_PROGRESS,
    FETCH_STATUS_FETCHED,
    FETCH_STATUS_FAILED,
]

PageStatusValue: TypeAlias = Literal[
    PAGE_STATUS_NEW,
    PAGE_STATUS_UNCHANGED,
    PAGE_STATUS_CHANGED,
    PAGE_STATUS_REMOVED,
    PAGE_STATUS_FAILED,
]
