from typing import Literal, TypeAlias


RESERVATION_OUTCOME_INSERTED = "inserted"
RESERVATION_OUTCOME_DEDUPLICATED = "deduplicated"
RESERVATION_OUTCOME_RUN_MISSING = "run_missing"
RESERVATION_OUTCOME_RUN_NOT_DISCOVERING = "run_not_discovering"

ReservationOutcomeValue: TypeAlias = Literal[
    RESERVATION_OUTCOME_INSERTED,
    RESERVATION_OUTCOME_DEDUPLICATED,
    RESERVATION_OUTCOME_RUN_MISSING,
    RESERVATION_OUTCOME_RUN_NOT_DISCOVERING,
]
